# Generated by Django 5.1.4 on 2024-12-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='resume_hash',
            new_name='resume',
        ),
    ]
